name: readsms
description: A flutter plugin that reads incoming SMS on device as a broadcast stream.
version: 0.0.2+2
homepage: "https://github.com/omarabdallah96/readsms_plugin"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.omarabdallah96.readsms
        pluginClass: ReadsmsPlugin
      ios:
        pluginClass: ReadsmsPlugin

